name: Daily Check-in

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to workspace root
        uses: actions/checkout@v3
        with:
          path: .   # 将仓库检出到 $GITHUB_WORKSPACE 根目录

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run checkin script
        env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
          COOKIE: ${{ secrets.COOKIE }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python checkin.py
