name: 18Comic Auto Checkin

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install selenium

      - name: Run checkin script
        env:
          COOKIE: ${{ secrets.COOKIE }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: python checkin.py
