name: 18comic 每日自动签到

on:
  schedule:
    # 每天 UTC 0 点运行一次（可根据需要调整 cron 表达式）
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到脚本
        env:
          COMIC_COOKIE: ${{ secrets.COMIC_COOKIE }}
          COMIC_USERNAME: ${{ secrets.COMIC_USERNAME }}
          COMIC_PASSWORD: ${{ secrets.COMIC_PASSWORD }}
        run: python checkin.py
